name: Test

on:
    push:
        branches: [main]
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Lint
              run: cargo clippy
            - name: cargo fmt
              run: cargo fmt --all -- --check
            - name: check typos
              uses: crate-ci/typos@master
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
